image: node:18
pages:
  stage: deploy
  cache:
    paths:
      - node_modules/
  script:
    # - apk add git # Uncomment this if you're using small docker images like alpine and have lastUpdated enabled
    - npm install
    - npm run docs:build
    #- yarn run build --base=$CI_PAGES_URL
    #- cp -a dist/. public/
  artifacts:
    paths:
      - public
  only:
    - main